name: test_env
channels:
  - conda-forge
dependencies:
  - python=3.5
  - xarray
  - dask
  - numpy > 1.13
  - pytest >= 4
  - future
  - matplotlib
  - cartopy >= 0.17
  - ffmpeg
  - pip:
    - codecov
    - pytest-cov
