name: test_env
channels:
  - conda-forge
dependencies:
  - python=3.5
  - xarray
  - dask
  - numpy > 1.13
<<<<<<< HEAD
  - pytest >= 4.4
=======
  - pytest >= 4
>>>>>>> 53cc1c8be4b36e2a5ecf70d8bf8b716fc6344d37
  - future
  - matplotlib
  - cartopy >= 0.17
  - ffmpeg
  - pip:
    - codecov
    - pytest-cov
