name: test_env
channels:
  - conda-forge
dependencies:
  - python=2.7
  - xarray
  - dask
  - numpy
  - pytest
  - future
  - matplotlib
  - cartopy
  - ffmpeg
  - pip:
    - codecov
    - pytest-cov
